@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json
@url = dogs

### GET ALL DOGS
GET http://{{host}}/{{url}}
Content-Type: application/json

### GET ALL DOGS WITH QUERY STRING
GET http://{{host}}/{{url}}?name=hound
Content-Type: application/json

### GET DOG WITH ID
GET http://{{host}}/{{url}}/1
Content-Type: application/json

### GET UNEXISTENT DOG
GET http://{{host}}/{{url}}/1000000
Content-Type: application/json


### POST DOG
POST http://{{host}}/{{url}}
Content-Type: application/json

{
    "weight": {
        "min": 3,
        "max": 6
    },
    "height": {
        "min": 23,
        "max": 29
    },
    "name": "Affenpinscher",
    "life_span": {
        "min": 10,
        "max": 12
    },
    "temperament": ["Stubborn", "Curious", "Playful", "Adventurous", "Active", "Fun-loving"]
}

### POST ANOTHER DOG
POST http://{{host}}/{{url}}
Content-Type: application/json

{
    "weight": {
        "min": 3,
        "max": 6
    },
    "height": {
        "min": 23,
        "max": 29
    },
    "name": "OtherHound",
    "life_span": {
        "min": 10,
        "max": 12
    },
    "temperament": ["Stubborn", "Independent", "Non-existent Temper"]
}

### POST SAME DOG, SHOULD NOT UPDATE
POST http://{{host}}/{{url}}
Content-Type: application/json

{
    "weight": {
        "min": 3,
        "max": 600
    },
    "height": {
        "min": 23,
        "max": 290
    },
    "name": "OtherHound",
    "life_span": {
        "min": 10,
        "max": 120
    },
    "temperament": ["Stubborn", "Curious", "Non-existent Temper"]
}

### DELETE DOG WITH ID
DELETE http://{{host}}/{{url}}/cb76b977-5d97-4d3a-985a-4bacc60eeb1e
Content-Type: application/json
