export const INIT_DOGS = 'INIT_DOGS'
export const SEARCH_BY_NAME_DOGS = 'SEARCH_BY_NAME_DOGS'
export const FILTER = 'FILTER'
export const ORDER = 'ORDER'
export const CLEAR = 'CLEAR'
export const CREATE_DOG = 'CREATE_DOG'
export const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT'